# Generated by Django 3.2.6 on 2022-03-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptancedocs',
            options={'verbose_name_plural': 'Acceptance documents'},
        ),
        migrations.AlterModelOptions(
            name='acceptancegoods',
            options={'verbose_name_plural': 'Acceptance goods'},
        ),
        migrations.AddField(
            model_name='acceptancegoods',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
