# Generated by Django 4.0.2 on 2022-03-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0002_auto_20220313_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptancegoods',
            old_name='price',
            new_name='purchase_price',
        ),
    ]
