# Generated by Django 4.0.2 on 2022-03-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0003_rename_price_acceptancegoods_purchase_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptancegoods',
            old_name='doc_id',
            new_name='document',
        ),
    ]
