# Generated by Django 4.0.2 on 2022-03-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldgoods',
            old_name='check_id',
            new_name='receipt_id',
        ),
    ]
